name: tides
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytest
  - matplotlib
  - notebook
  - mdanalysis 
  - pip
  - pip:
      - pyscf
      - git+https://github.com/frobnitzem/hirshfeld

